### ISSUE TITLE
onnxruntime problem!

### ISSUE THREAD

**Issue by Aljumaili85** [Jamiroquai88/VBDiarization#25]
Hi,
First , thanks for developing this tool !, i hope to get full benefit from it.
Successfully I have installed all the requirements that has been mentioned in the requirements.txt and the vbdiar package; but I got an error while running the run.sh . I think its  matter of package version of onnxruntime .
below is the error :
`  
- [Traceback (most recent call last):
  File "diarization.py", line 268, in <module>
    n_jobs=1)
  File "diarization.py", line 78, in process_files
    ret = _process_files((fns, kwargs))
  File "diarization.py", line 48, in _process_files
    ret.append(process_file(file_name=fn, **kwargs))
  File "diarization.py", line 134, in process_file
    embedding_set = extract_embeddings(features_dict, embedding_extractor)
  File "/home/sipalmidi/Desktop/kaldi_project/kaldi_env/lib/python3.6/site-packages/vbdiar/embeddings/embedding.py", line 27, in extract_embeddings
    embeddings = embedding_extractor.features2embeddings(features_dict)
  File "/home/sipalmidi/Desktop/kaldi_project/kaldi_env/lib/python3.6/site-packages/vbdiar/kaldi/onnx_xvector_extraction.py", line 54, in features2embeddings
    xvec = self.sess.run(None, {self.input_name: data_dict[name].T[np.newaxis, :, :]})[0]
  File "/home/sipalmidi/Desktop/kaldi_project/kaldi_env/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 136, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: 0 for the following indices
 index: 2 Got: 121 Expected: 100
 Please fix either the inputs or the model.
 ]  `

could you please mention the package versions used in your code!

**Comment by Aljumaili85** [comment]
sorry, it was already answered , I will close it, thanks
