### ISSUE TITLE
Dataset in repository is different as compared to onnx file. 

### ISSUE THREAD

**Issue by arpit2020** [Jamiroquai88/VBDiarization#28]
Onnx file is generated with AMI corpus dataset but the data set available in repository to run the application is different.
Due to which while running the application i am getting this error

return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: 0 for the following indices
 index: 2 Got: 121 Expected: 100
 Please fix either the inputs or the model.

Actually the command in run.sh file is
"python3.7 diarization.py -c ../configs/vbdiar.yml \
    -l lists/list_spk.scp \
    --audio-dir wav/fisher-english-p1 \
     --vad-dir vad/fisher-english-p1 \
     --mode diarization \
     --out-emb-dir embeddings"

where as on github link is 

"python diarization.py -c ../configs/vbdiar.yml -l lists/AMI_dev-eval.scp --audio-dir wav/AMI/IHM_SUM --vad-dir vad/AMI --out-emb-dir emb/AMI/IHM_SUM --in-rttm-dir rttms/AMI"

**Comment by sravanco** [comment]
@arpit2020 Any luck fixing this error? I'm now having the same issue.

**Comment by haha010508** [comment]
I got same error!

**Comment by haha010508** [comment]
pip install onnxruntime==0.3.0, it was worked

**Comment by arpit2020** [comment]
@haha010508   with onnxruntime==0.3.0 i start getting new error
**raise TypeError(message)
TypeError: Expected sequence or array-like, got <class 'NoneType'>**

**Comment by Jamiroquai88** [comment]
ONNX file has nothing with AMI, it is x-vector architecture trained on voxcelebs.
do you still have some issues? I think it looks like you are putting there some unexpected inputs, if you want me to replicate that, you will need to specify more information

**Comment by zajacm** [comment]
I'm facing exactly the same issues as described above. I think the root case is in mismatch between external libraries versions. All dependencies are not binned to any version and even Python version was not provided. I have no clue what is the exact setup to get it working. 

Python 3.8 result:
```
(base) root@57dc2f29d23d:/VBDiarization/examples# bash run.sh
/opt/conda/lib/python3.8/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.8/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
2020-09-05 13:50:39,341 - __main__ - INFO - Running `diarization.py -c ../configs/vbdiar.yml -l lists/list_spk.scp --audio-dir wav/fisher-english-p1 --vad-dir vad/fisher-english-p1 --mode diarization --out-emb-dir embeddings`.
/opt/conda/lib/python3.8/site-packages/vbdiar/utils/utils.py:428: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(ymlfile)
2020-09-05 13:50:39,435 - __main__ - INFO - Processing file fe_03_00001-a.
2020-09-05 13:50:39,436 - vbdiar.kaldi.mfcc_features_extraction - INFO - Extracting MFCC features from `/VBDiarization/examples/wav/fisher-english-p1/fe_03_00001-a.wav`.
2020-09-05 13:50:39,490 - vbdiar.vad.vad - INFO - Loading VAD from file `/VBDiarization/examples/vad/fisher-english-p1/fe_03_00001-a.lab.gz`.
2020-09-05 13:50:39,495 - vbdiar.kaldi.onnx_xvector_extraction - INFO - Extracting x-vectors from 4 segments.
Traceback (most recent call last):
  File "diarization.py", line 263, in <module>
    process_files(
  File "diarization.py", line 78, in process_files
    ret = _process_files((fns, kwargs))
  File "diarization.py", line 48, in _process_files
    ret.append(process_file(file_name=fn, **kwargs))
  File "diarization.py", line 134, in process_file
    embedding_set = extract_embeddings(features_dict, embedding_extractor)
  File "/opt/conda/lib/python3.8/site-packages/vbdiar/embeddings/embedding.py", line 27, in extract_embeddings
    embeddings = embedding_extractor.features2embeddings(features_dict)
  File "/opt/conda/lib/python3.8/site-packages/vbdiar/kaldi/onnx_xvector_extraction.py", line 54, in features2embeddings
    xvec = self.sess.run(None, {self.input_name: data_dict[name].T[np.newaxis, :, :]})[0]
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/session.py", line 142, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: 0 for the following indices
 index: 2 Got: 121 Expected: 100
 Please fix either the inputs or the model.
```

Downgraded to `Python3.7` and `onnxruntime==0.3.0`:
```
(branch-env) root@57dc2f29d23d:/VBDiarization/examples# bash run.sh
/opt/conda/envs/branch-env/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
/opt/conda/envs/branch-env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
2020-09-05 14:16:07,720 - __main__ - INFO - Running `diarization.py -c ../configs/vbdiar.yml -l lists/list_spk.scp --audio-dir wav/fisher-english-p1 --vad-dir vad/fisher-english-p1 --mode diarization --out-emb-dir embeddings`.
/opt/conda/envs/branch-env/lib/python3.7/site-packages/vbdiar/utils/utils.py:428: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(ymlfile)
2020-09-05 14:16:07,842 - __main__ - INFO - Processing file fe_03_00001-a.
2020-09-05 14:16:07,843 - vbdiar.kaldi.mfcc_features_extraction - INFO - Extracting MFCC features from `/VBDiarization/examples/wav/fisher-english-p1/fe_03_00001-a.wav`.
2020-09-05 14:16:07,915 - vbdiar.vad.vad - INFO - Loading VAD from file `/VBDiarization/examples/vad/fisher-english-p1/fe_03_00001-a.lab.gz`.
2020-09-05 14:16:07,920 - vbdiar.kaldi.onnx_xvector_extraction - INFO - Extracting x-vectors from 4 segments.
2020-09-05 14:16:07,998 - __main__ - INFO - Processing file fe_03_00001-b.
2020-09-05 14:16:07,999 - vbdiar.kaldi.mfcc_features_extraction - INFO - Extracting MFCC features from `/VBDiarization/examples/wav/fisher-english-p1/fe_03_00001-b.wav`.
2020-09-05 14:16:08,096 - vbdiar.vad.vad - INFO - Loading VAD from file `/VBDiarization/examples/vad/fisher-english-p1/fe_03_00001-b.lab.gz`.
2020-09-05 14:16:08,104 - vbdiar.kaldi.onnx_xvector_extraction - INFO - Extracting x-vectors from 4 segments.
2020-09-05 14:16:08,166 - vbdiar.scoring.diarization - INFO - Loading pickled evaluation embedding from `embeddings`.
2020-09-05 14:16:08,166 - vbdiar.scoring.diarization - INFO - Loading evaluation pickle file `fe_03_00001-a`.
2020-09-05 14:16:08,166 - vbdiar.scoring.diarization - INFO - Loading evaluation pickle file `fe_03_00001-b`.
2020-09-05 14:16:08,168 - vbdiar.scoring.diarization - INFO - Scoring using `PLDA`.
2020-09-05 14:16:08,168 - vbdiar.scoring.diarization - INFO - Clustering `fe_03_00001-a` using 3 long embeddings.
Traceback (most recent call last):
  File "diarization.py", line 294, in <module>
    result = diar.score_embeddings(args.min_window_size, args.max_num_speakers, args.mode)
  File "/opt/conda/envs/branch-env/lib/python3.7/site-packages/vbdiar/scoring/diarization.py", line 210, in score_embeddings
    centroids = self.run_clustering(num_speakers, embeddings_long)
  File "/opt/conda/envs/branch-env/lib/python3.7/site-packages/vbdiar/scoring/diarization.py", line 243, in run_clustering
    n_clusters=num_speakers, n_init=100, n_jobs=1).fit(embeddings)
  File "/opt/conda/envs/branch-env/lib/python3.7/site-packages/spherecluster/spherical_kmeans.py", line 363, in fit
    return_n_iter=True,
  File "/opt/conda/envs/branch-env/lib/python3.7/site-packages/spherecluster/spherical_kmeans.py", line 189, in spherical_k_means
    random_state=random_state,
  File "/opt/conda/envs/branch-env/lib/python3.7/site-packages/spherecluster/spherical_kmeans.py", line 39, in _spherical_kmeans_single_lloyd
    sample_weight = _check_sample_weight(X, sample_weight)
  File "/opt/conda/envs/branch-env/lib/python3.7/site-packages/sklearn/utils/validation.py", line 1215, in _check_sample_weight
    n_samples = _num_samples(X)
  File "/opt/conda/envs/branch-env/lib/python3.7/site-packages/sklearn/utils/validation.py", line 147, in _num_samples
    raise TypeError(message)
TypeError: Expected sequence or array-like, got <class 'NoneType'>
```

Full `pip freeze` output:
```
pip freeze
attrs==20.2.0
certifi==2020.6.20
cycler==0.10.0
importlib-metadata==1.7.0
iniconfig==1.0.1
joblib @ file:///tmp/build/80754af9/joblib_1594236160679/work
kaldiio==2.15.1
kiwisolver==1.2.0
matplotlib==3.3.1
mkl-fft==1.1.0
mkl-random==1.1.1
mkl-service==2.3.0
more-itertools==8.5.0
nose==1.3.7
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1596233707986/work
onnxruntime==0.3.0
packaging==20.4
Pillow==7.2.0
pluggy==0.13.1
py==1.9.0
pyclustering==0.10.0.1
pyparsing==2.4.7
pytest==6.0.1
python-dateutil==2.8.1
PyYAML==5.3.1
scikit-learn==0.22
scipy @ file:///tmp/build/80754af9/scipy_1597686620742/work
six==1.15.0
spherecluster==0.1.7
toml==0.10.1
vbdiar==0.3
zipp==3.1.0
```

@Jamiroquai88 could you provide `pip freeze` and Python version when it works for you? It will be really helpful. 

Thanks!

**Comment by Jamiroquai88** [comment]
could you please try python3.6?

**Comment by zajacm** [comment]
The issue still persists (`python3.6`):
```
(py-36-env) root@8ec50741c73e:/app/VBDiarization/examples# python3 diarization.py -c ../configs/vbdiar.yml     -l lists/list_spk.scp     --audio-dir wav/fisher-english-p1      --vad-dir vad/fisher-english-p1      --mode diarization      --out-emb-dir embeddings
/opt/conda/envs/py-36-env/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
/opt/conda/envs/py-36-env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
2020-09-06 12:04:14,183 - __main__ - INFO - Running `diarization.py -c ../configs/vbdiar.yml -l lists/list_spk.scp --audio-dir wav/fisher-english-p1 --vad-dir vad/fisher-english-p1 --mode diarization --out-emb-dir embeddings`.
/opt/conda/envs/py-36-env/lib/python3.6/site-packages/vbdiar/utils/utils.py:428: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(ymlfile)
2020-09-06 12:04:14,342 - __main__ - INFO - Processing file fe_03_00001-a.
2020-09-06 12:04:14,343 - vbdiar.kaldi.mfcc_features_extraction - INFO - Extracting MFCC features from `/app/VBDiarization/examples/wav/fisher-english-p1/fe_03_00001-a.wav`.
2020-09-06 12:04:14,478 - vbdiar.vad.vad - INFO - Loading VAD from file `/app/VBDiarization/examples/vad/fisher-english-p1/fe_03_00001-a.lab.gz`.
2020-09-06 12:04:14,488 - vbdiar.kaldi.onnx_xvector_extraction - INFO - Extracting x-vectors from 4 segments.
2020-09-06 12:04:14,563 - __main__ - INFO - Processing file fe_03_00001-b.
2020-09-06 12:04:14,564 - vbdiar.kaldi.mfcc_features_extraction - INFO - Extracting MFCC features from `/app/VBDiarization/examples/wav/fisher-english-p1/fe_03_00001-b.wav`.
2020-09-06 12:04:14,616 - vbdiar.vad.vad - INFO - Loading VAD from file `/app/VBDiarization/examples/vad/fisher-english-p1/fe_03_00001-b.lab.gz`.
2020-09-06 12:04:14,625 - vbdiar.kaldi.onnx_xvector_extraction - INFO - Extracting x-vectors from 4 segments.
2020-09-06 12:04:14,659 - vbdiar.scoring.diarization - INFO - Loading pickled evaluation embedding from `embeddings`.
2020-09-06 12:04:14,662 - vbdiar.scoring.diarization - INFO - Loading evaluation pickle file `fe_03_00001-a`.
2020-09-06 12:04:14,665 - vbdiar.scoring.diarization - INFO - Loading evaluation pickle file `fe_03_00001-b`.
2020-09-06 12:04:14,672 - vbdiar.scoring.diarization - INFO - Scoring using `PLDA`.
2020-09-06 12:04:14,672 - vbdiar.scoring.diarization - INFO - Clustering `fe_03_00001-a` using 3 long embeddings.
Traceback (most recent call last):
  File "diarization.py", line 294, in <module>
    result = diar.score_embeddings(args.min_window_size, args.max_num_speakers, args.mode)
  File "/opt/conda/envs/py-36-env/lib/python3.6/site-packages/vbdiar/scoring/diarization.py", line 210, in score_embeddings
    centroids = self.run_clustering(num_speakers, embeddings_long)
  File "/opt/conda/envs/py-36-env/lib/python3.6/site-packages/vbdiar/scoring/diarization.py", line 243, in run_clustering
    n_clusters=num_speakers, n_init=100, n_jobs=1).fit(embeddings)
  File "/opt/conda/envs/py-36-env/lib/python3.6/site-packages/spherecluster/spherical_kmeans.py", line 363, in fit
    return_n_iter=True,
  File "/opt/conda/envs/py-36-env/lib/python3.6/site-packages/spherecluster/spherical_kmeans.py", line 189, in spherical_k_means
    random_state=random_state,
  File "/opt/conda/envs/py-36-env/lib/python3.6/site-packages/spherecluster/spherical_kmeans.py", line 39, in _spherical_kmeans_single_lloyd
    sample_weight = _check_sample_weight(X, sample_weight)
  File "/opt/conda/envs/py-36-env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 1215, in _check_sample_weight
    n_samples = _num_samples(X)
  File "/opt/conda/envs/py-36-env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 147, in _num_samples
    raise TypeError(message)
TypeError: Expected sequence or array-like, got <class 'NoneType'>
```

Could you just provide output from both commands `python --V` and `pip freeze`? I think it will be the most valuable thing what we can do at this moment.

**Comment by Jamiroquai88** [comment]
```bash
python -V
```
```
Python 3.6.8 :: Anaconda, Inc.
```

```bash
pip freeze
```
```
atomicwrites==1.3.0
attrs==19.1.0
certifi==2019.3.9
cycler==0.10.0
kaldiio==2.13.4
kiwisolver==1.0.1
matplotlib==3.0.3
more-itertools==7.0.0
nose==1.3.7
numpy==1.16.2
onnxruntime==0.3.0
Pillow==5.4.1
pluggy==0.9.0
py==1.8.0
pyclustering==0.8.2
pyparsing==2.3.1
pytest==4.3.1
python-dateutil==2.8.0
PyYAML==5.1
scikit-learn==0.20.3
scipy==1.2.1
six==1.12.0
spherecluster==0.1.7
-e git+https://github.com/Jamiroquai88/VBDiarization.git@506bc1b1e9f3c2825486e1274d0440b5348a33ff#egg=vbdiar
```

**Comment by Jamiroquai88** [comment]
I would expect some differences in `spherecluster` library, try to use the version I have.

**Comment by Jamiroquai88** [comment]
Closee due to inactivity.
