### ISSUE TITLE
error running example run.sh

### ISSUE THREAD

**Issue by rnunziata** [Jamiroquai88/VBDiarization#8]
Not sure why I am getting this error: I am running ubuntu16 python 3.5

```
./run.sh 
Traceback (most recent call last):
  File "diarization.py", line 18, in <module>
    from vbdiar.vad import get_vad
  File "/home/rjn/anaconda3/envs/pyannote/lib/python3.6/site-packages/vbdiar/vad/__init__.py", line 8, in <module>
    from vad import load_vad_lab_as_bool_vec, get_vad
ImportError: cannot import name 'load_vad_lab_as_bool_vec'

```

**Comment by Jamiroquai88** [comment]
Hi, I am not sure, but try this in `vbdiar/vad/__ini__.py`
```python
from .vad import load_vad_lab_as_bool_vec, get_vad
```

**Comment by rnunziata** [comment]
also had to do same in  embeddings/__init__.py
then
got the following error which I fixed by changing cPickle to piclle

```
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
```
The last error is:

./run.sh

does the run.sh need some modification?
```

 /home/rjn/anaconda3/envs/pyannote/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
usage: Extract embeddings used for diarization from audio wav files.
       [-h] -l INPUT_LIST -c CONFIGURATION [--audio-dir AUDIO_DIR]
       [--vad-dir VAD_DIR] [--in-emb-dir IN_EMB_DIR]
       [--out-emb-dir OUT_EMB_DIR] [--norm-list NORM_LIST]
       [--in-rttm-dir IN_RTTM_DIR] [--out-rttm-dir OUT_RTTM_DIR]
       [-wav-suffix WAV_SUFFIX] [-vad-suffix VAD_SUFFIX]
       [-rttm-suffix RTTM_SUFFIX] [--min-window-size MIN_WINDOW_SIZE]
       [--max-window-size MAX_WINDOW_SIZE] [--vad-tolerance VAD_TOLERANCE]
       [-j NUM_THREADS] [--max-num-speakers MAX_NUM_SPEAKERS]
Extract embeddings used for diarization from audio wav files.: error: the following arguments are required: -l/--input-list



```

**Comment by Jamiroquai88** [comment]
Hi, looks like code is not working for python3 but should work in python2.7. Since I switched to python3.6 recently, I will eventually rewrite whole library to use python3.6, but I am not able to estimate when it is going to happen. My suggestion for now is to use python2.7 or I would definitely consider a merge request for python3 compatibility

**Comment by rnunziata** [comment]
I am now trying pytlhon2 I've gotten further but have different error:

```
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_3/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named _tkinter

```
